# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BncKvYEtjrkevH6Ih1x1_7KyZ30KOA0r
"""

score = input().split()
count = 0
for e in score:
  if int(e)>0 and int(e)<=100:
    if int(e)<60:
      count+=1
print(count)